<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE internationalization [
<!ELEMENT text (#PCDATA)>
<!ATTLIST text key ID #REQUIRED>
]>
<Internationalization langCode="es">
	
	<text key="headerPresenter_languageNameAbbreviation">
		Es
	</text>

	<!-- SSOOrbitMetadataCallback -->
	<text key="SSOOrbitMetadataCallback_retrievingOrbitPoints">
		Recuperando puntos de la &#243;rbita de $SSONAME$...
	</text>

	<!-- countRequestCallback -->
	<text key="CountRequestCallback_countingAvailableData">
		Contando datos disponibles...
	</text>

	<!-- publicationsSourcesCallback -->
	<text key="PublicationsSourcesCallback_retrievingPubSources">
		Obteniendo objetos con publicaciones...
	</text>

	<!-- publicationsBySourceCallback -->
	<text key="PublicationsBySourceCallback_retrievingPubsOf">
		Obteniendo publicaciones de $NAME$...
	</text>

	<text key="tabulator_retrievingMissionData">
		Obteniendo datos de $NAME$...
	</text>
	<text key="MetadataCallback_retrievingSSOMetadata">
		Obteniendo metadatos de $NAME$...
	</text>

	<!-- searchPanel -->
	<text key="searchPanel_inputByTargetName">
		Ejemplos de entrada por nombre de destino:
	</text>
	<text key="searchPanel_solarSystemObjects">
		Objetos del Sistema Solar:
	</text>
	<text key="searchPanel_inputByName">
		Por nombre:
	</text>
	<text key="searchPanel_inputByObjectNumber">
		Por n&#250;mero de objeto:
	</text>
	<text key="searchPanel_inputByCoordinates">
		Ejemplos de entrada por coordenadas:
	</text>
	<text key="searchPanel_wrongCoordsInput">
		Error al interpretar las coordenadas. Revise los
		formatos permitidos.
	</text>
	<text key="searchPanel_targetNotFound">
		No encontrado.
	</text>
	<text key="searchPanel_ssoTargetNotFound">
		Objeto del Sistema Solar no encontrado.
	</text>
	<text key="searchPanel_seeMoreExamples">
		Ver m&#225;s ejemplos
	</text>
	<text key="searchPanel_search">
		Buscar...
	</text>

	<!-- searchPresenter_resolvingTarget -->
	<text key="searchPresenter_resolvingTarget">
		Buscando $NAME$...
	</text>

	<!-- uploadTargetList -->
	<text key="uploadTargetList_targetList">
		Lista de objetos:
	</text>
	<text key="uploadTargetList_uploadTargetList">
		Subir lista
	</text>
	<text key="uploadTargetList_uploadTargetListFailed">
		Fallo debido a
	</text>
	<text key="uploadTargetList_title">
		Lista de objetos
	</text>

	<!-- uploadTargetListPanel -->
	<text key="uploadTargetListPanel_MultiTargetCatalog">
		Cat&#225;logo Multi-Objeto
	</text>

	<!-- Sky -->
	<text key="sky_wavelength">
		Longitud de onda
	</text>
	<text key="sky_selectWavelength">
		Seleccione longitud de onda
	</text>
	<text key="sky_skies">
		Cielos
	</text>
	<text key="sky_selectSky">
		Seleccione cielos
	</text>
	<text key="sky_selectASky">
		Seleccione un cielo.
	</text>
	<text key="sky_skyDetails">
		Detalles del cielo.
	</text>
	<text key="sky_removeSky">
		Eliminar cielo.
	</text>
	<text key="sky_loadingSkies">
		Cargando cielo...
	</text>

	<!-- treeMap -->
	<text key="treeMap_ASTRO_IMAGING">
		Observaciones
	</text>
	<text key="treeMap_ASTRO_CATALOGUE">
		Cat&#225;logos
	</text>
	<text key="treeMap_ASTRO_SPECTRA">
		Espectros
	</text>
	<text key="treeMap_SSO">
		Observaciones de objetos del Sistema Solar (OSS)
	</text>
	<text key="treeMap_loading_ASTRO_IMAGING">
		Cargando observaciones...
	</text>
	<text key="treeMap_loading_ASTRO_CATALOGUE">
		Cargando cat&#225;logos...
	</text>
	<text key="treeMap_loading_ASTRO_SPECTRA">
		Cargando espectros...
	</text>
	<text key="treeMap_loading_SSO">
		Cargando observaciones del Sistema Solar...
	</text>
	<text key="treeMap_noData_ASTRO_IMAGING">
		No se encontraron observaciones.
	</text>
	<text key="treeMap_noData_ASTRO_CATALOGUE">
		No se encontraron entradas de cat&#225;logo.
	</text>
	<text key="treeMap_noData_ASTRO_SPECTRA">
		No se encontraron datos espectrales.
	</text>
	<text key="treeMap_noData_SSO">
		No se encontraron observaciones del Sistema Solar.
	</text>
	<text key="treeMap_nameOfSelectedLabel">
		OSS: $SSONAME$ ($SSOTYPE$)
	</text>
	
	<text key="treeMap_notInRange_ASTRO_IMAGING">
		Ninguna im&#225;gen encontrada en este rango de longitudes de onda.
	</text>
	<text key="treeMap_notInRange_ASTRO_CATALOGUE">
		Ningun cat&#225;logo encontrado en este rango de longitudes de onda.
	</text>
	<text key="treeMap_notInRange_ASTRO_SPECTRA">
		Ning&#xFA;n Dato espectral encontrado en este rango de longitudes de onda. 
	</text>
	<text key="treeMap_notInRange_SSO">
		Ninguna observaci&#xF3;n de objetos del sistema solar encontrada en este rango de longitudes de onda.
	</text>

	<!-- HiPS Details Popup -->
	<text key="hiPSDetailsPopup_mapName">
		Nombre del mapa:
	</text>
	<text key="hiPSDetailsPopup_mission">
		Misi&#243;n:
	</text>
	<text key="hiPSDetailsPopup_instrument">
		Instrumento:
	</text>
	<text key="hiPSDetailsPopup_wavFreq">
		Longitud de onda / frecuencia:
	</text>
	<text key="hiPSDetailsPopup_mapCreatedBy">
		Mapa creado por
	</text>
	<text key="hiPSDetailsPopup_forMoreInformation">
		Para m&#225;s informaci&#243;n haga clic&amp;nbsp;
	</text>
	<text key="hiPSDetailsPopup_here">
		aqu&#237; </text>
	<text key="hiPSDetailsPopup_close">
		Cerrar
	</text>

	<!-- Change Palette Button -->
	<text key="changePaletteBtn_changePaletteTooltip">
		Paleta de colores
	</text>

	<!-- abstractTablePanel -->
	<text key="tabulator_preview">
		Previsualizar
	</text>

	<!-- commonObservationTablePanel -->
	<text key="tabulator_sendRowToVOA">
		Enviar fila a una aplicaci&#243;n de observatorio
		virtual
	</text>

	<!-- planObservationPanel -->
	<text key="planObservationPanel_projectFutureObservations">
		Proyectar futuras observaciones con $MISSION$
	</text>
	<text key="planObservationPanel_helpMessageTitle">
		Proyectar futuras observaciones
	</text>

	<!-- futureFootprintRow -->
	<text key="futureFootprintRow_addJWSTInstrument">
		Agregar un instrumento del JWST.
	</text>
	<text key="futureFootprintRow_rotation">
		Rotaci&#243;n
	</text>
	<text key="futureFootprintRow_allInstruments">
		Todos los instrumentos
	</text>
	<text key="futureFootprintRow_removeFootprint">
		Eliminar esta huella
	</text>
	<text key="futureFootprintRow_increase">
		Aumenta
	</text>
	<text key="futureFootprintRow_angleBy">
		&#193;ngulo
	</text>
	<text key="futureFootprintRow_decrease">
		Disminuye
	</text>
	<text key="futureFootprintRow_copyCoordinatesAndData">
		Copiar coordenadas y datos
	</text>
	<text key="futureFootprintRow_centre">
		Centro
	</text>
	<text key="futureFootprintRow_coordinateSystem">
		Sistema de coordenadas:
	</text>
	<text key="futureFootprintRow_dataCopiedToClipboard">
		Datos copiados al portapapeles.
	</text>
	<text key="futureFootprintRow_aperture">
		Abertura
	</text>

	<!-- screenShotDialogBox -->
	<text key="screenShotDialogBox_screenshot">
		Captura de pantalla
	</text>

	<!-- ctrlToolBar -->
	<text key="ctrlToolBar_URLClipboard">
		URL copiada al portapapeles
	</text>

	<!-- ctrlToolBarPresenter -->
	<text key="ctrlToolBarPresenter_bibcode">
		C&#243;digo de publicaci&#243;n: $HTML$
	</text>
	<text key="ctrlToolBarPresenter_authors">
		Autores: $HTML$
	</text>
	<text key="ctrlToolBarPresenter_journal">
		Revista: $JOURNAL$, $DATE$
	</text>
	<text key="ctrlToolBarPresenter_pubSources">
		Objetos citados en la publicaci&#243;n:
	</text>
	<text key="ctrlToolBarPresenter_adsSearch">
		Busqueda en ADS: $HTML$
	</text>
	<text key="ctrlToolBarPresenter_authorSources">
		Objetos relacionados con el autor:
	</text>
	<text key="ctrlToolBarPresenter_loadingAuthorSources">
		Buscando fuentes en las publicaciones de $AUTHOR$
	</text>

	<!-- playerPanel -->
	<text key="playerPanel_next">
		Siguiente
	</text>
	<text key="playerPanel_pause">
		Pausa
	</text>
	<text key="playerPanel_play">
		Reproducir
	</text>
	<text key="playerPanel_previous">
		Anterior
	</text>
	<text key="playerPanel_surveyTourStarted">
		Tour comenzado
	</text>

	<!-- sampConstants -->
	<text key="sampConstants_help">
		Ayuda sobre informaci&#243;n de interoperabilidad (SAMP)
	</text>
	<text key="sampConstants_sendingViaSamp">
		Enviando @@ v&#237;a SAMP
	</text>

	<!-- webConstants -->
	<text key="webConstants_manageSkies">
		Administrar cielos
	</text>
	<text key="webConstants_learnMore">
		&#161;Aprenda m&#225;s sobre ESASky!
	</text>
	<text key="webConstants_trackSSO">
		Seguimiento de objetos del Sistema Solar a trav&#233;s
		del cuadro de b&#250;squeda
	</text>
	<text key="webConstants_projectFutureObservations">
		Proyecte observaciones futuras
	</text>
	<text key="webConstants_explorePublications">
		Examine las publicaciones sobre esta regi&#243;n
	</text>
	<text key="webConstants_exploreRandomTarget">
		Investigue un objeto aleatorio
	</text>

	<!-- displayUtils -->
	<text key="displayUtils_connectivityProblems">
		Problema de conectividad
	</text>
	<text key="displayUtils_VOnotFound">
		No se ha encontrado ninguna herramienta compatible con
		el Observatorio Virtual (VO) activa en su ordenador.
	</text>
	<text key="displayUtils_startOneOf">
		Lance una de las siguientes aplicaciones:
	</text>
	<text key="displayUtils_seeHelp">
		Por favor, lea la ayuda para m&#225;s detalles.
	</text>
	<text key="displayUtils_tryAgain">
		Una vez que se est&#233; ejecutando cualquiera de estas
		aplicaciones, int&#233;ntelo de nuevo.
	</text>

	<!-- resultsPresenter -->
	<text key="resultsPresenter_computingDataCrossMatch">
		Cruzando datos para $SSOTEXT$
	</text>

	<!-- closeableTabLayoutPanel -->
	<text key="closeableTabLayoutPanel_closeTab">
		Cerrar pesta√±a
	</text>
	<text key="closeableTabLayoutPanel_saveResultsTableOrDownload">
		Guarde la tabla de resultados o descargue los productos
		seleccionados
	</text>
	<text key="closeableTabLayoutPanel_sendTableToVOA">
		Enviar la tabla a una aplicaci&#243;n de observatorio
		virtual
	</text>
	<text key="closeableTabLayoutPanel_recentre">
		Volver a centrar
	</text>
	<text key="closeableTabLayoutPanel_refreshData">
		Actualizar datos
	</text>
	<text key="abstractTablePanel_filterTooltip">
		Filtro
	</text>

	<!-- targetWidget -->
	<text key="targetWidget_showTargetInTheSky">
		Mostrar objeto en el cielo
	</text>
	<text key="targetWidget_targetNotFoundInSimbad">
		Objeto no encontrado en Simbad.
	</text>

	<!-- welcomeDialog -->
	<text key="WelcomeDialog_title">
		&#161;Bienvenido a ESASky!
	</text>
	<text key="WelcomeDialog_description">
		ESASky es una aplicaci&#243;n que le permite visualizar
		y descargar datos astron&#243;micos p&#250;blicos.
	</text>
	<text key="WelcomeDialog_closeButton">
		Cerrar
	</text>

	<!-- allSkyPanel -->
	<text key="AllSkyPanel_fovButton">
		Introducir FoV manualmente con decimales
	</text>

	<!-- allSkyPresenter -->
	<text key="AllSkyPresenter_futureSelectedDetectorCatalog">
		Cat&#225;logo de detectores futuros seleccionados
	</text>

	<text key="AllSkyFocusPanel_searchIn">
		Buscar en
	</text>

	<!-- fovDialogBox -->
	<text key="FovDialogBox_inputFoVTextBox">
		Introduce el tama&#241;o del campo de visi&#243;n (con
		decimales)
	</text>
	<text key="FovDialogBox_wrongFov">
		&#161;S&#243;lo n&#250;meros y puntos!
	</text>

	<!-- zoomControlPanel -->
	<text key="ZoomControlPanel_zoomIn">
		Acercarse
	</text>
	<text key="ZoomControlPanel_zoomOut">
		Alejarse
	</text>

	<!-- EsaSkyNumberControl -->
	<text key="EsaSkyNumberControl_increaseWithLabel">
		Aumentar $TITLE$ un factor $STEP$
	</text>
	<text key="EsaSkyNumberControl_decreaseWithLabel">
		Disminuir $TITLE$ un factor $STEP$
	</text>

	<!-- saveAllView -->
	<text key="saveAllView_save_In_VOTABLE_Format">
		VOTable
	</text>
	<text key="saveAllView_save_In_VOTABLE_Format_Title">
		Guardar como tabla XML VO
	</text>
	<text key="saveAllView_save_In_CSV_Format">
		CSV
	</text>
	<text key="saveAllView_save_In_CSV_Format_Title">
		Guardar como CSV, Valores Separados por Comas
	</text>
	<text key="saveAllView_Download_Btn_Text">
		Descargar datos de productos
	</text>
	<text key="saveAllView_Download_Btn_Title">
		Descargar productos seleccionados
	</text>
	<text key="saveAllView_Rows_Selected_Label">
		$COUNT$ fila(s) seleccionadas en la pesta&#241;a actual
	</text>

	<!-- pointInformation -->
	<text key="PointInformation_to">
		$FROM$ a $TO$
	</text>

	<!-- multiTargetTooltip -->
	<text key="MultiTargetTooltip_nearestSimbadId">
		Objeto m&#225;s cercano en Simbad
	</text>

	<!-- planningDetectorCenterTooltip -->
	<text key="PlanningDetectorCenterTooltip_instrument">
		Instrumento:
	</text>
	<text key="PlanningDetectorCenterTooltip_detector">
		Detector:
	</text>
	<text key="PlanningDetectorCenterTooltip_referenceRA">
		RA de referencia:
	</text>
	<text key="PlanningDetectorCenterTooltip_referenceDEC">
		DEC de referencia:
	</text>
	<text key="SoftX-ray">
		Rayos X Blandos
	</text>
	<text key="HardX-ray">
		Rayos X Duros
	</text>
	<text key="UV">
		UV
	</text>
	<text key="Ultraviolet">
		Ultravioleta
	</text>
	<text key="Optical">
		&#211;ptico
	</text>
	<text key="NearIR">
		IR cercano
	</text>
	<text key="MidToFarIR">
		IR medio a lejano
	</text>
	<text key="FarIR">
		IR lejano
	</text>
	<text key="NearInfrared">
		Infrarrojo cercano
	</text>
	<text key="MidToFarInfrared">
		Infrarrojo medio a lejano
	</text>
	<text key="FarInfrared">
		Infrarrojo lejano
	</text>
	<text key="Submm">
		Submm
	</text>
	<text key="Submillimeter">
		Submilim&#233;trico
	</text>
	<text key="Radio">
		Radio
	</text>
	<text key="pubDate">
		Fecha de publicaci&#243;n
	</text>
	<text key="BIBCODE">
		C&#243;digo de publicaci&#243;n
	</text>
	<text key="Title">
		T&#237;tulo
	</text>
	<text key="Authors">
		Autores
	</text>
	<text key="Journal">
		Revista
	</text>
	<text key="Date">
		Fecha
	</text>
	
	<text key="header_learnMore">
		&#161;Aprenda m&#225;s sobre ESASky!
	</text>
	<text key="header_getURLCurrentView">
		Obtener la URL de la vista actual
	</text>
	<text key="header_viewInWWTAbbr">
		Ver en WWT
	</text>
	<text key="header_viewInWWTFull">
		Ver en WorldWide Telescope
	</text>
	<text key="header_takeScreenshotFull">
		Hacer una captura de pantalla de la vista actual
	</text>
	<text key="header_takeScreenshot">
		Captura de pantalla
	</text>
	<!-- menuPanel -->
	<text key="header_videoTutorials">
		Tutoriales en v&#237;deo
	</text>
	<text key="header_comunity">
		Comentarios
	</text>
	<text key="header_aboutUs">
		Sobre nosotros
	</text>
	<text key="header_releaseNotes">
		Notas de publicaci&#243;n
	</text>
	<text key="header_newsletter">
		Bolet&#237;n de noticias
	</text>
	<text key="header_sciMode">
		Modo cient&#237;fico
	</text>
	<text key="header_share">
		Compartir
	</text>
	<text key="header_help">
		Ayuda
	</text>

	<text key="PublicationsBySourceCallback_helpTitle">
		Publicaciones
	</text>
	<text key="resultsPresenter_helpDescription_PUBLICATIONS_ADS-PUB">
		Publicaciones asociadas a esta fuente en SIMBAD, y
		acceso a las fuentes de cada publicaci&#243;n.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#publications"
		target="_blank"&gt;
		Documentaci&#243;n completa de esta funcionalidad.
		&lt;/a&gt; </text>

	<text key="uploadTargetList_targetListDescriptionText">
		Seleccione una lista de ejemplo, o suba un fichero de
		texto
		que contenga su lista de objetos, ya sea nombres reconocidos por
		SIMBAD
		o una lista de coordenadas.
		Mientras se carga la lista, el
		mensaje 'Resolviendo lista de objetos...'
		aparecer&#225; en la parte
		superior de la interfaz; una vez cargada,
		la lista aparecer&#225; a la
		izquierda.
		&lt;br&gt;&lt;br&gt;
		Pinche en
		un objeto para visualizarlo en
		el cielo.
		Si un objeto no ha sido reconocido por SIMBAD,aparecer&#225;
		tachado.
		Debajo de la lista aparecen unos botones de v√≠deo.
		Pulse
		&#9654;
		para avanzar autom√°ticamente por la lista de objetos;
		el objeto
		mostrado en cada momento aparecer&#225; resaltado en color
		gris oscuro.
		Es posible a&#241;adir texto y comentarios a una lista de objetos;
		este texto se mostrar&#225; en ESASky en una ventana emergente.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-target-lists"
		target="_blank"&gt;
		Pinche aqu&#237; para ver el formato requerido y
		algunos ficheros de ejemplo.
		&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#list"
		target="_blank"&gt;
		Documentaci&#243;n completa de esta funcionalidad.
		&lt;/a&gt; </text>

	<text key="uploadTargetList_selectList">
		Seleccionar lista
	</text>
	<text key="uploadTargetList_orUpload">
		or
	</text>
	<text key="sky_selectSky_help">
		Los cielos est&#225;n agrupados en rangos de longitud de
		onda,
		de rayos Gamma a Radio, y en una secci&#243;n &quot;Otros&quot;
		que
		actualmente contiene modelos f&#237;sicos.
		Para seleccionar un
		cielo, escoja el rango de longitud de onda en el
		primer men&#250;,
		y
		navegue entre los cielos del segundo men&#250;.
		Pinche en el icono de
		la &quot;i&quot; para conocer los detalles de cada cielo.
		Para m&#225;s
		informaci&#243;n y una lista de los cielos (HiPS)
		disponibles,
		vaya a la
		p&#225;gina correspondiente de la documentaci&#243;n general.
		&lt;br&gt;&lt;br&gt;
		La paleta de colores del cielo puede modificarse
		con las opciones
		'Nativa', 'EOSB', 'Planck',
		'Rainbow', 'Escala de
		grises' y 'Cubehelix'.
		&lt;br&gt;&lt;br&gt;
		Es posible a&#241;adir un
		cielo a la lista mediante
		el bot&#243;n +.
		&lt;br&gt;&lt;br&gt;
		Pulse los
		botones de v&#237;deo para visualizar autom&#225;ticamente los
		distintos cielos de la lista, pasar al siguiente, al anterior o parar.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#skies"
		target="_blank"&gt;
		Documentaci&#243;n completa de esta funcionalidad.
		&lt;/a&gt; </text>

	<text key="dateFilter_resetFilter">
		Quitar filtro
	</text>
	<text key="rangeFilter_resetFilter">
		Quitar filtro
	</text>
	<text key="planObservationPanel_helpMessageText">
		Esta herramienta proyecta en el cielo las huellas de
		instrumentos
		astron&#243;micos
		en la posici&#243;n y orientaci&#243;n
		elegidas.
		Ha sido desarrollada para ayudar a los astr&#243;nomos
		profesionales
		a preparar sus propuestas de observaci&#243;n para una
		misi&#243;n
		espacial
		o telescopio terrestre determinado.
		Actualmente, la
		herramienta ofrece todos los instrumentos del JWST,
		incluyendo la
		posibilidad de proyectar el plano focal del JWST al completo.
		Las
		huellas de instrumentos de otras misiones operativas
		se
		implementar&#225;n en un futuro cercano.
		&lt;br&gt;&lt;br&gt;
		IMPORTANTE: Esta funcionalidad no reemplaza la herramienta ATP del
		JWST.
		Su prop&#243;sito es tan s&#243;lo proporcionar una ayuda a los
		astr&#243;nomos
		cuyas observaciones con el JWST requieran solapamiento
		con observaciones ya existentes de otras misiones
		disponibles en
		ESASky, o que quieran cerciorarse de que sus observaciones,
		ya sean con
		un solo instrumento o en paralelo,
		cubren/evitan ciertas zonas u
		objetos en las regiones a observar.
		Las coordenadas y &#225;ngulos de
		posici&#243;n definidos mediante esta
		herramienta
		deben de ser
		comprobados y refinados en la APT,
		que sigue siendo la herramienta
		oficial para preparar observaciones con
		el JWST.
		Para m&#225;s
		informaci&#243;n y para la instalaci&#243;n de la APT, vaya
		a
		&lt;a
		href="//www.stsci.edu/hst/proposing/apt" target="_blank"&gt;
		esta
		p&#225;gina del STScI&lt;/a&gt;; para conocer m&#225;s detalles
		de los
		distintos instrumentos del JWST,
		&lt;a
		href="//jwst.stsci.edu/instrumentation" target="_blank"&gt;
		haga clic
		aqu&#237;.&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.youtube.com/watch?v=n2iW1HfVgVE&amp;feature=youtu.be"
		target="_blank"&gt;
		Tambi&#233;n puede ver el siguiente v&#237;deo: How
		to plan future JWST
		observations&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#planning"
		target="_blank"&gt;
		Documentaci&#243;n completa de esta funcionalidad.
		&lt;/a&gt; </text>
	<text key="ctrlToolBarPresenter_showingMaxSources">
		Mostrando s&#243;lo las primeras $COUNT$ fuentes
	</text>
	<text key="ctrlToolBarPresenter_loadPublicationDetails">
		Cargando detalles de las publicaciones
	</text>
	<text key="ctrlToolBarPresenter_retrievingPublicationTargetList">
		Obteniendo la lista de objetos
	</text>
	<text key="webConstants_uploadTargetList">
		Administre una lista de objetos
	</text>
	<text key="webConstants_exploreImageObservations">
		Examine las im&#225;genes de esta regi&#243;n
	</text>
	<text key="webConstants_exploreCatalogue">
		Examine los datos de cat&#225;logo de esta regi&#243;n
	</text>
	<text key="webConstants_exploreSpectral">
		Examine los datos espectrales de esta regi&#243;n
	</text>
	<text key="webConstants_exploreData">
		Examine los datos para $TARGET$
	</text>
	<text key="displayUtils_toCommunicateWithDS9">
		Para comunicarse con DS9, es necesario lanzar
		tambi&#233;n una
	</text>
	<text
		key="resultsPresenter_helpDescription_ASTRO_IMAGING_INTEGRAL">
		Las observaciones de INTEGRAL/IBIS consisten
		en un gran n&#250;mero
		de exposiciones (&quot;science windows&quot;)
		en torno a la
		posici&#243;n de un objeto.
		Por este motivo, y a causa del gran campo
		del instrumento IBIS,
		no resulta pr&#225;ctico mostrar las huellas
		geom&#233;tricas de todas
		estas exposiciones.
		En lugar de eso, ESASky
		muestra las posiciones centrales
		de cada una de las observaciones,
		las
		cuales enlazan con la lista completa de exposiciones asociadas con
		ella.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#INTEGRAL"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text
		key="resultsPresenter_helpDescription_ASTRO_IMAGING_XMM-EPIC">
		Las observaciones de XMM-Newton son productos de alto nivel del
		Processing Pipeline System (PPS) presentes en el archivo
		cient&#237;fico de la misi&#243;n
		(&lt;a
		href="//nxsa.esac.esa.int/nxsa-web/#home"
		target="_blank"&gt;XSA&lt;/a&gt;).
		Los datos incluidos son las
		im&#225;genes de alto nivel
		combinadas de las tres c&#225;maras (EPIC
		PN, EPIC MOS1 y EPIC MOS2)
		en la banda de energ&#237;a 0.2-12 keV.
		Los
		criterios de selecci&#243;n se basan en la existencia
		de una imagen
		p&#250;blica combinada de alto nivel.
		Los mosaicos de subapuntado han
		sido excluidos,
		pero se incluye el mosaico combinado completo.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#XMM-Newton-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_ASTRO_IMAGING_Chandra">
		El conjunto de datos de Chandra incluye todas las
		observaciones
		p&#250;blicas
		(im&#225;genes y espectros), hasta el 8 de
		octubre de 2017,
		de los instrumentos ACIS, LETG, HETG y HRC,
		disponibles en el archivo de datos de Chandra a trav&#233;s de Chaser
		(&lt;a
		href="//cda.harvard.edu/chaser/"
		target="_blank"&gt;cda.harvard.edu/chaser/&lt;/a&gt;).
		Para obtener
		informaci&#243;n detallada de la misi&#243;n Chandra y sus
		productos,
		consulte el sitio web:
		&lt;a href="//cxc.harvard.edu/"
		target="_blank"&gt;
		cxc.harvard.edu/&lt;/a&gt;.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#Chandra-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_ASTRO_IMAGING_SUZAKU">
		Las observaciones incluyen todas las im&#225;genes
		p&#250;blicas
		presentes en el archivo de SUZAKU en DARTS.
		Para obtener
		informaci&#243;n detallada de la misi&#243;n SUZAKU y sus
		productos,
		visite:
		&lt;a href="//www.darts.isas.jaxa.jp/astro/suzaku/"
		target="_blank"&gt;
		www.darts.isas.jaxa.jp/astro/suzaku/&lt;/a&gt;.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#SUZAKU-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text
		key="resultsPresenter_helpDescription_ASTRO_IMAGING_XMM-OM-OPTICAL">
		Los datos del
		&lt;a
		href="//www.cosmos.esa.int/web/xmm-newton/technical-details-om"
		target="_blank"&gt;
		Optical Monitor
		&lt;/a&gt;
		(OM) en ESASky son
		observaciones p&#250;blicas
		con al menos un producto de alto nivel,
		donde las im&#225;genes individuales por filtro se combinan
		y alinean
		al Norte.
		En ESASky se incluyen los siguientes tipos de im&#225;genes
		de OM:
		Modo por defecto RSIMAG (RSIMAG),
		marco completo a baja
		resoluci&#243;n (LSIMAG),
		marco completo a alta resoluci&#243;n
		(HSIMAG),
		y definida por el usuario (USIMAG).
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#OM-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text
		key="resultsPresenter_helpDescription_ASTRO_IMAGING_XMM-OM-UV">
		Los datos del
		&lt;a
		href="//www.cosmos.esa.int/web/xmm-newton/technical-details-om"
		target="_blank"&gt;
		Optical Monitor
		&lt;/a&gt;
		(OM) en ESASky son
		observaciones p&#250;blicas
		con al menos un producto de alto nivel,
		donde las im&#225;genes individuales por filtro se combinan
		y alinean
		al Norte.
		En ESASky se incluyen los siguientes tipos de im&#225;genes
		de OM:
		Modo por defecto RSIMAG (RSIMAG),
		marco completo a baja
		resoluci&#243;n (LSIMAG),
		marco completo a alta resoluci&#243;n
		(HSIMAG),
		y definida por el usuario (USIMAG).
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#OM-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
		
	<text key="resultsPresenter_helpDescription_ASTRO_IMAGING_HST-OPTICAL">
		Los datos observacionales del Telescopio Espacial Hubble
		(HST)
		proporcionados por ESASky son productos cient&#237;ficos
		de las
		dos colecciones de datos de Hubble:
		&lt;ul&gt;
		&lt;li&gt;
		&lt;span&gt;
		La colecci&#243;n HST est&#225;ndar
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;li&gt;
		&lt;span&gt;
		La colecci&#243;n del Hubble Legacy
		Archive (HLA)
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;/ul&gt;
		ESASky aplica un filtro en los datos de archivo
		del HST
		para mostrar en primer lugar todas las im&#225;genes compuestas
		(asociaciones)
		y despu&#233;s todas las im&#225;genes individuales
		(&quot;HST
		singleton&quot;)
		que no forman parte de ninguna
		asociaci&#243;n.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HST-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
		
	<text key="resultsPresenter_helpDescription_ASTRO_IMAGING_HST-UV">
		Los datos observacionales del Telescopio Espacial Hubble
		(HST)
		proporcionados por ESASky son productos cient&#237;ficos
		de las
		dos colecciones de datos de Hubble:
		&lt;ul&gt;
		&lt;li&gt;
		&lt;span&gt;
		La colecci&#243;n HST est&#225;ndar
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;li&gt;
		&lt;span&gt;
		La colecci&#243;n del Hubble Legacy
		Archive (HLA)
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;/ul&gt;
		ESASky aplica un filtro en los datos de archivo
		del HST
		para mostrar en primer lugar todas las im&#225;genes compuestas
		(asociaciones)
		y despu&#233;s todas las im&#225;genes individuales
		(&quot;HST
		singleton&quot;)
		que no forman parte de ninguna
		asociaci&#243;n.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HST-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
		
	<text key="resultsPresenter_helpDescription_ASTRO_IMAGING_HST-IR">
		Los datos observacionales del Telescopio Espacial Hubble
		(HST)
		proporcionados por ESASky son productos cient&#237;ficos
		de las
		dos colecciones de datos de Hubble:
		&lt;ul&gt;
		&lt;li&gt;
		&lt;span&gt;
		La colecci&#243;n HST est&#225;ndar
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;li&gt;
		&lt;span&gt;
		La colecci&#243;n del Hubble Legacy
		Archive (HLA)
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;/ul&gt;
		ESASky aplica un filtro en los datos de archivo
		del HST
		para mostrar en primer lugar todas las im&#225;genes compuestas
		(asociaciones)
		y despu&#233;s todas las im&#225;genes individuales
		(&quot;HST
		singleton&quot;)
		que no forman parte de ninguna
		asociaci&#243;n.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HST-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text
		key="resultsPresenter_helpDescription_ASTRO_IMAGING_Herschel">
		Los datos de Herschel disponibles incluyen
		todas las observaciones
		p&#250;blicas de los instrumentos HIFI, PACS y
		SPIRE
		(incluidas las
		observaciones paralelas PACS/SPIRE).
		Los datos cient&#237;ficos que se
		obtienen son &quot;Standalone Browse
		Products&quot;.
		M&#225;s abajo se
		proporciona una breve descripci&#243;n de estos productos.
		Pinche
		&lt;a
		href="//www.cosmos.esa.int/web/herschel/data-products-overview"
		target="_blank"&gt;
		aqu&#237;
		&lt;/a&gt;
		para m&#225;s informaci&#243;n
		sobre los datos de Herschel.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HERSCHEL-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_ASTRO_IMAGING_ISO">
		El Infrared Space Observatory (ISO), lanzado en
		noviembre de 1995,
		fue el primer aut&#233;ntico observatorio infrarrojo
		orbital.
		Transportaba cuatro instrumentos cient&#237;ficos:
		dos
		espectr&#243;metros (SWS y LWS),
		un fotopolar&#237;metro de imagen
		(ISOPHOT) y una c&#225;mara (ISOCAM).
		Las &#250;nicas im&#225;genes
		proporcionadas a trav&#233;s de ESASky
		son las de ISOCAM.
		Los datos
		espectrosc&#243;picos proceden de los cuatro instrumentos.

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#ISO-OBS"
		target="_blank"&gt;
		M&#225;s informaci&#243;n
		&lt;/a&gt; </text>

	<text
		key="resultsPresenter_helpDescription_ASTRO_CATALOGUE_INTEGRAL">